// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the extension/azurekeyvaultbasicauth component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("azurekeyvaultbasicauth")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/extension/azurekeyvaultbasicauthextension"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
